public enum ResponseType {
    matchFound,
    unitMoved,
    cardInserted,
    specialPowerUsed,
    collectableUsed,
    PlayerForfeited,
    unitSelected,
    unitAttacked,
    unitAndEnemyAttacked,
    player1Won,
    player2Won,
    turnChanged,

    sendMessage,
    close,
    signUp,
    login,
    logout,
    leaderBoard,
    updateLeaderBoard,
    shop,
    buy,
    sell
}
